name: Build works.json

on:
  push:
    paths:
      - 'オロチポートフォリオ文字データ/オロチポートフォリオ表.csv'
      - 'converter.js'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Generate works.json
        run: node converter.js
      - name: Ensure output exists
        run: test -f "オロチポートフォリオ文字データ/works.json"
      - name: Sanity check count
        run: |
          node -e "const fs=require('fs');const w=JSON.parse(fs.readFileSync('オロチポートフォリオ文字データ/works.json','utf8')); if(!Array.isArray(w)||w.length<10){console.error('too few items',w?.length); process.exit(1);} console.log('count',w.length);"
      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "オロチポートフォリオ文字データ/works.json"
          git commit -m "chore: auto-update works.json" || echo "no changes"
          git push
